name: ghcr-push

on:
  push:
    branches:
      - main

jobs:
  gh-package:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo into the runner
        uses: action/checkout@v4

      - name: GHCR Login
        uses: docker/login-action@v3
        with:
          registery: ghcl.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      steps:
        - name: Build and Push 
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ghcr.io/${{ github.repository }}:latest 
